### ISSUE TITLE
The github repository used probably shouldn't be hardcoded

### ISSUE THREAD

**Issue by jvlaar** [grrr-amsterdam/golem#2]
In Golem_GitHelper the following constants are defined:

```
const GIT_LS_CMD_BITBUCKET    = 'git ls-remote git@bitbucket.org:grrr/%s';
const GIT_LS_CMD_GITHUB       = 'git ls-remote git@github.com:grrr-amsterdamr/%s.git';
const GIT_CLONE_CMD_BITBUCKET = 'git clone git@bitbucket.org:grrr/%s %s --recursive';
const GIT_CLONE_CMD_GITHUB    = 'git clone git@github.com:grrr-amsterdam/%s.git %s --recursive';
```

This makes it impossible to use Golem when you're working outside of the grrr-amsterdam repo.

**Comment by harmenjanssen** [comment]
You're right. Historically the `golem build` command accepted a second parameter for the repository. I've reinstated it.   
The `golem checkout` command for already populated projects now accepts a `--repo` flag to overwrite the hard-coded Grrr repositories.

Usage:

```
golem checkout my_project --repo=git@github.com:username/my_repo.git
golem build my_project git@github.com:username/my_repo.git
```
